### ISSUE TITLE
MIT license unclear due to throttle-debounce dependency license

### ISSUE THREAD

**Issue by robinpilz** [remirror/remirror#2248]
### Summary

We are currently facing the issue that we use the tiptap editor in our software and when analyzing the licenses of it an external attorney found that the license for the dependency `throttle-debounce` of  `@remirror/core-helpers` is unclear for us to use and distribute without open sourcing our company code due to the GPL license.

We already reached out to the author of `throttle-debounce` and did not get an answer, therefore I would like to mention it in this repo aswell as it would also affect the MIT license of remirror from my understanding.

So maybe there would be a way for you guys to switch to a different lib that offers throttle and debounce functionality like lodash or even use a custom implementation for it. Or maybe even an agreement with the author, that you are able to use it under the MIT license would be enough.

Was not sure how to label it, so for now its a bug but feel free to label it otherwise

![2024-04-03 12_39_12-en json - ecosys (Workspace)  WSL_ Ubuntu-20 04  - Visual Studio Code](https://github.com/remirror/remirror/assets/60291821/148a10f5-7bdb-4df1-a2d9-c9c027d01e07)

**Comment by robinpilz** [comment]
> The author of throttle-debounce has responded to this in the past. See [niksy/throttle-debounce#40 (comment)](https://github.com/niksy/throttle-debounce/issues/40#issuecomment-662852843).

Unfortunately this is not enough as it is just an assumption and not an actual statement from the original author who decided to go with the 2 licenses

**Comment by kainosnoema** [comment]
We also just got bit by this during due-diligence. Can we expect a resolution?

**Comment by seanf** [comment]
See also https://github.com/niksy/throttle-debounce/pull/65

**Comment by whawker** [comment]
Resolved by https://github.com/remirror/remirror/pull/2245

**Comment by laneciar** [comment]
Still a little confused on this, on the latest version of 3.0.1 but still seeing the dependency:
`"node_modules/@remirror/core-helpers": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/@remirror/core-helpers/-/core-helpers-4.0.0.tgz",
      "integrity": "sha512-w90bJ+SLim25DWLN0Y6KjBwDhSgyzWwPxazwHQj7s3Px9dF69sG4cq3nA8RP2TCq1CV4bZmtW4+hCV26pHvgeA==",
      "dependencies": {
        "@remirror/core-constants": "3.0.0",
        "@remirror/types": "2.0.0",
        "@types/object.omit": "^3.0.0",
        "@types/object.pick": "^1.3.2",
        "@types/throttle-debounce": "^2.1.0",
        "case-anything": "^2.1.13",
        "clsx": "^2.1.1",
        "dash-get": "^1.0.2",
        "deepmerge": "^4.3.1",
        "fast-deep-equal": "^3.1.3",
        "make-error": "^1.3.6",
        "object.omit": "^3.0.0",
        "object.pick": "^1.3.0",
        "throttle-debounce": "^3.0.1"
      }
    },`
    
    Does the PR you link confirm that throttle-debounce is now MIT? I noticed that they have released newer versions that looks like they removed GPL from the LICENSE.txt but it looks like this version still has the GPL text in the LICENSE.txt.

**Comment by LoneRifle** [comment]
> Resolved by #2245

That PR only resolves the issue for `prosemirror-trailing-node`. Other packages on this repo that are dependent on `@remirror/core-helpers` are still legally affected.
