### ISSUE TITLE
Cursor "skips over" empty block quotes

### ISSUE THREAD

**Issue by benjie** [remirror/remirror#795]
### Summary

Cursor "skips over" empty block quotes

### Steps to reproduce

Enter the following into Remirror playground, then click at the top or bottom of the document and press the up/down arrow once or twice.

```
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "blockquote",
        "content": [
          {
            "type": "paragraph",
            "content": [
              {
                "type": "text",
                "text": "sdf"
              }
            ]
          }
        ]
      },
      {
        "type": "blockquote"
      },
      {
        "type": "blockquote"
      },
      {
        "type": "blockquote"
      },
      {
        "type": "blockquote"
      },
      {
        "type": "blockquote"
      },
      {
        "type": "blockquote",
        "content": [
          {
            "type": "paragraph"
          },
          {
            "type": "paragraph",
            "content": [
              {
                "type": "text",
                "text": "sdf"
              }
            ]
          }
        ]
      }
    ]
  },
  "playground": {
    "m": 1,
    "c": "import { useRemirrorPlayground } from \"@remirror/playground\";\nimport React, { FC, useMemo } from \"react\";\nimport { BlockquoteExtension } from \"remirror/extension/blockquote\";\nimport { RemirrorProvider, useManager, useRemirror } from \"remirror/react\";\nimport { useKeymap } from \"remirror/react/hooks\";\nimport { baseKeymap } from '@remirror/pm/commands';\n\nimport {convertCommand} from 'remirror/core';\n\nconst EXTENSIONS = () => [new BlockquoteExtension()];\n\n\n/**\n * This component contains the editor and any toolbars/chrome it requires.\n */\nconst SmallEditor: FC = () => {\n  const { getRootProps } = useRemirror();\n  useKeymap(useMemo(() => ({\n    //  'Enter'() {alert('Enter'); return false},\n    'Shift-Enter': convertCommand(baseKeymap.Enter),\n  }), [convertCommand, baseKeymap ]));\n\n\n  return (\n    <div>\n      <div {...getRootProps()} />\n    </div>\n  );\n};\n\nconst SmallEditorContainer = () => {\n  const extensionManager = useManager(EXTENSIONS);\n\n  const { value, onChange } = useRemirrorPlayground(extensionManager); // Delete this line\n\n  return (\n    <RemirrorProvider\n      manager={extensionManager}\n      value={value}\n      onChange={onChange}\n    >\n      <SmallEditor />\n    </RemirrorProvider>\n  );\n};\n\nexport default SmallEditorContainer;\n"
  }
}
```

### Expected results

Cursor moves between the empty blockquotes allowing you to type into them

### Actual results

Cursor jumps over (most) of the blockquotes, so you cannot reach them.

### Screenshot(s)

![Peek 2020-11-19 12-37](https://user-images.githubusercontent.com/129910/99667259-0aba2680-2a64-11eb-813e-4a60cb0a89e4.gif)

**Comment by benjie** [comment]
Also you can't click in the empty block quotes (if you do the cursor appears but then immediately jumps)

**Comment by whawker** [comment]
@benjie I think this may have been fixed by #937 ?

**Comment by benjie** [comment]
@whawker It's still an issue in the playground right now; has that fix shipped there yet?

**Comment by whawker** [comment]
By the look of things, I think the playground is running on the `next` branch rather than `beta`?

I've created a [CodeSandbox here](https://codesandbox.io/s/wild-brook-332qb?file=/src/App.js) to demo, it doesn't correct the _initial_ state (copied from your initial post), but create blockquotes/deleting text etc seems to work as I'd expected.

Do you have reproduction steps for how you got the document into the state in your initial post in the first place?

**Comment by benjie** [comment]
It seems merging the blockquotes has been improved so I cannot reproduce this initial state via the editor any more. So solving this might be as simple as applying whatever block merging we have going on in the editor now to the initial state.
